### ISSUE TITLE
Change control mode when CTRL+C is press on xbot2-core terminal

### ISSUE THREAD

**Issue by MarcoMagriDev** [ADVRHumanoids/modularbots_fraunhofer#4]
Suppose that I am controlling the robot in effort mode (with zero stiffness and damping), if somebody stops the `xbot2-core` terminal using CTRL+C the robot remains in effort control mode and the last commanded effort is kept as reference. 

Instead, I would like to have the chance to switch the control mode to position (restoring stiffness and damping values with a procedure similar to the one proposed in `stopping` method of your gcomp_example). I have already tried to use the `on_abort` method without success. Can you please provide an hint on how to achieve this "graceful abort" in case of effort control mode?

**Comment by EdoardoRomiti** [comment]
Hi @MarcoMagriDev I tried replicating the issue, but I couldn't.
The `abort` is immediate, differently form the `stop`, so I did not do any stiffness transition. I just reset the original stiffness immediately, and this worked. You can have a try with that, the robot will show a small jump when "aborting" but will stay up.

If you have already tried this, this means the issue must come from having older versions of XBot, and this behavior you have experienced has been fixed in the newest. We haven't updated your version since the first deployment at FHI, so we can try to do that at ICRA or find some other solution.
FYI @alaurenzi

**Comment by MarcoMagriDev** [comment]
Hi @EdoardoRomiti could you please share the sample plugin that you have used? 
Just to make sure that i'm not doing something wrong.

Thanks.

**Comment by EdoardoRomiti** [comment]
Here is the example I used, which is now in the `xbot2_examples` repo: https://github.com/ADVRHumanoids/xbot2_examples/blob/v2.10/src/gcomp_example/gcomp_example.cpp
This uses the new version of xbot v2.10

**Comment by MarcoMagriDev** [comment]
the new xbot2 version solves the issue. Closing
